# 可視化


- tidyverseに含まれるggplot2パッケージ[@R-ggplot2]を利用

```{r}
library(tidyverse)
```


- 引き続きcausaldataに含まれるclose_collegeを使用

```{r}
data("close_college",
     package = "causaldata")

raw <- close_college

raw <- mutate(raw,
              college = if_else(educ >= 16,"More than college","Less than college"))
```

## Y=連続、X＝カテゴリ

### ヒストグラム: geom_histogram (tidyverse)

- 医療機関の利用回数

```{r}
ggplot(raw, 
       aes(x = lwage)
       ) +
  geom_histogram()
```

- 学歴別賃金分布

```{r}
ggplot(raw, 
       aes(x = lwage,
           fill = college)
       ) +
  geom_histogram(position = "identity",
                 alpha = 0.5)
```

- 人種・学歴別の賃金分布

```{r}
ggplot(raw, 
       aes(x = lwage,
           fill = college)
       ) +
  geom_histogram(position = "identity",
                 alpha = 0.5
                 ) +
  facet_wrap(~ black)
```

### 密度: geom_density (tidyverse)

- 人種・学歴別の賃金分布

```{r}
ggplot(raw, 
       aes(x = lwage,
           fill = college)
       ) +
  geom_density(position = "identity",
                 alpha = 0.5
  ) +
  facet_wrap(~ black)
```

### Boxplot: geom_boxplot (tidyverse)

```{r}
ggplot(raw,
       aes(y = lwage,
           x = college)
       ) +
  geom_boxplot()
```

## Y=連続、X=連続

### 散布図: geom_point (tidyverse)

- 散布図：連続変数間の関係性を可視化する図

```{r}
ggplot(raw,
       aes(x = exper,
           y = lwage)
       ) +
  geom_point()
```

- サンプルサイズが大きくなると機能しない

### ヒートマップ: geom_bin2d (tidyverse)

- 代替案はヒートマップ

```{r}
ggplot(raw,
       aes(x = exper,
           y = lwage)
       ) +
  geom_bin2d()
```
