# 比較・因果推論

- Chapter \@ref(unique)-\@ref(panel) の背後にある問題意識・方針を紹介

- Chapter \@ref(comparison) では本ページにおける「グループ間の比較」を具体的に定義し、その推定が抱える論点を明示する。

- Chapter \@ref(causal) では因果推論の問題を、識別の問題と推定の問題に大別し、代表的な論点を示す。

## 比較 {#comparison}

### 問題設定

- 条件付きの比較：変数$D_i$の値が異なる集団間において、結果変数$Y_i$の分布がどの程度異なっているのか、推定する。
その際に、直接的な関心ではない変数群$X_i$を”一定”とする。

- 以下の議論では$Y_i$の平均値に焦点を当て、$E[Y_i|D_i=d,X_i]-E[Y_i|D_i=d',X_i]$の推定を目指す。
またこの際に点推定量のみならず、信頼区間の推定も行います。

### 推定上の問題

- 有限のサンプルを用いて、多数の$X_i,D_i$で条件づけた平均値を推定するためには、なんらかの工夫が必要

- 依然として広く用いられている手法は、研究者により設定された線形モデルを重回帰で推定する方法

$$E[Y_i|D_i=d,X_i=x]=\underbrace{\beta_d\times d + \beta_0 + \beta_1\times x_1+...+\beta_L \times x_L}_{線形モデル}$$

- 設定された線形モデル重回帰の推定目標を条件付き平均値の線形近似と見做す"Agnostic view" [@angrist2002covariance;@angrist2008mostly]が、重回帰を利用する説得的な理由となっている。

  - ”正しい”回帰モデルの定式化が難しい社会科学分野においては、条件付き平均値の”真”のモデルを設定することは事実上不可能であるため

- しかしながら以下のような場合、深刻な問題が生じることが知られている。

1. 異なる$D$グループ間で、$X$の分布が異なる。
  
2. 多数の$X$について、条件づける必要がある。

- 1の問題を緩和するために、推定の前処理としてマッチングを行うことが有力な方法となる。
  
- 2の問題が深刻な場合、伝統的なマッチングの手法の有効性は失われる。
この問題を回避するためにChapter \@ref(general) では、LASSOやRandom Forestなどの予測手法の応用を紹介する。

## 因果効果 {#causal}

### 問題設定

- ある集団の変数$D$を変化させた場合、結果変数$Y$の分布がどのように変化するのか、因果効果を推定する。

- 潜在結果モデルを用いて定義する

  - $Y_i(d)$: 回答者$i$の原因変数が$d$であったときの結果変数値
  
  - $Y_i(d)-Y_i(d')$: 原因変数が$d'$から$d$に変化することの個人因果効果

### 識別の問題

- 因果効果を推定する際には、識別を議論する必要がある。

  - 識別：「仮にサンプルサイズが無限大である」場合、どのような仮定の下で因果効果を推定できるか？

#### Selection-on-observable
  
- Chapter \@ref(unique) - \@ref(hetero)では以下の仮定に基づき議論していきます。

  - $0<\Pr[D_i=d|X_i]<1$: サブグループにおいても、原因変数の値にバリエーションが存在する。
  
  - $X$で条件づけた場合、潜在結果関数と原因変数の実現値が独立している$Y_i(d)\perp D_i|X_i=x$
  
    - 十分条件：同じ$X$グループ内では、$D$の値がランダムに決定されている

- 以上の仮定のもとで$D$の因果効果は、$E[Y|D=d,X]-E[Y|D=d',X]$によって識別できる。

#### Regression discontinuity

- Chapter \@ref(RD)では以下の仮定に基づく手法を紹介

  - $D=\{0,1\}$とし、ある連続変数$X$についてcutoff$c$が存在するとする
  
  - $\lim_{x\uparrow c}\Pr[D_i=1|X_i=x]=1$, $\lim_{x\downarrow c}\Pr[D_i=1|X_i=x]=0$ (Sharp discontinuity)
  
    - より一般的には、原因変数の分布がcutoffの近傍で不連続に変化していれば推定できる (Fuzzy discontinuity)
    
  - $\lim_{x\uparrow c}\Pr[Y_i(d)|X_i=x]= \lim_{x\downarrow c}\Pr[Y_i(d)|X_i=x]$
  
    - 潜在結果変数の分布はcutofffの近傍で連続的に変化している

- 以上の条件の下で、cutoff$c$上の因果効果は以下のように識別される

$$E[Y_i(1)-Y_i(0)|X_i=c]=\lim_{x\uparrow c}E[Y_i|X_i=x]-\lim_{x\downarrow c}E[Y_i|X_i=x]$$

#### Pallarel trend

- Chapter \@ref(panel)　では平行トレンドに基づく推定方法を紹介する。

- 2期間のパネルデータを想定し、Treatment/Control groupが存在するとする。

  - 原因変数の値は以下を満たす。 $D_{i\in T,0}=D_{i\in C,0}=0$、$D_{i\in T,1}=1, D_{i\in C,1}=0$、ただし$i\in T$はTreatment、$i\in C$はControl groupに所属することを示す。
  
  - $E[Y_{i\in T,1}(0)-Y_{i\in T,0}(0)]=E[Y_{i\in C,1}(0)-Y_{i\in C,0}(0)]$

### 推定の問題

- Selection-on-observableに基づく推定では、比較と同じような推定上の問題を抱え、その解決策も共有する。

- Regression discontinuityでは、$\lim_{x\uparrow c}E[Y_i|X_i=x]$、$\lim_{x\downarrow c}E[Y_i|X_i=x]$を以下に推定するかが問題となる。Chapter \@ref(panel) ではもっとも標準的な局所的な外挿による推定法を紹介する
