# マッチング推定

- MatchIt [@R-MatchIt]パッケージを使った実装を紹介

## データ

```{r}
library(tidyverse)

data("close_college",
     package = "causaldata")

raw <- na.omit(close_college)

raw <- mutate(raw,
              college = if_else(educ >= 16, 1, 0))

set.seed(111)
```

## パッケージ

```{r}
library(MatchIt)
library(estimatr)
```


## Exacet Matching

```{r}

fit.m <- matchit(college ~ black + smsa + south + nearc4,
                 data = raw,
                 method = "exact")
```

### Balance check

```{r}
sum.m <- summary(fit.m)

plot(sum.m, xlim=c(0,2))
```

### estimation

```{r}
df <- match.data(fit.m)

lm_robust(lwage ~ college + nearc4 + black + smsa + south,
          df,
          weights = weights)
```

## Coarsened exacet Matching

- Coarsened exact matching法 [@iacus2012causal] の実装

```{r}

fit.m <- matchit(college ~ black + smsa + south + nearc4 + exper,
                 data = raw,
                 method = "cem")
```

### Balance check

```{r}
sum.m <- summary(fit.m)

plot(sum.m, xlim=c(0,2))
```

### estimation

- マッチング後の推定 [@abadie2021robust]

```{r}
df <- match.data(fit.m)

lm_robust(lwage ~ college + nearc4 + black + smsa + south + exper,
          df,
          weights = weights)
```

