# 条件付き平均効果関数の推定


```{r}
library(tidyverse)

data("close_college",
     package = "causaldata")

raw <- na.omit(close_college)

raw <- mutate(raw,
              college = if_else(educ >= 16, 1, 0))

Y <- as.numeric(raw$lwage)

D <- as.numeric(raw$college)

X <- model.matrix(~ 0 + nearc4 + black + smsa + south,
                  raw)
```


## Casual Forest

```{r}
library(grf)

fit <- regression_forest(X = X,
                         Y = Y)

Y.hat <- predict(fit)$predictions

fit <- regression_forest(X = X,
                         Y = D)

D.hat <- predict(fit)$predictions

fit.CF <- causal_forest(X = X,
                        W = D,
                        Y = Y,
                        Y.hat = Y.hat,
                        W.hat = D.hat,
                        tune.parameters = "all")

tau.grf <- predict(fit.CF)$predictions
```

## Baysian causal forest

```{r}
library(bcf)
```

```{r}
fit.BCF <- bcf(y = Y,
               z = D,
               x_control = X,
               pihat = D.hat,
               nburn=2000,
               nsim=2000
               )

tau.bcf <- fit.BCF$tau
```


```{r}
average_treatment_effect(fit.CF,
                         subset = tau.grf >= quantile(tau.grf, probs = 0.8)
                         )
```


```{r}
average_treatment_effect(fit.CF,
                         subset = colMeans(tau.bcf) >= quantile(colMeans(tau.bcf), probs = 0.8)
                         )
```



```{r}
average_treatment_effect(fit.CF,
                         subset = tau.grf < median(tau.grf)
                         )
```


```{r}
average_treatment_effect(fit.CF,
                         subset = colMeans(tau.bcf) < median(colMeans(tau.bcf))
                         )
```
