# Panel data

## パッケージ

```{r}
library(tidyverse)
library(estimatr)
library(AER) 
library(did) # weighted two-way fixed effect
```

## Data

- AERパッケージに含まれるパネルデータPSID7682を利用

  - 595名の回答者について、1976年から1983年までの7期間パネルデータ

```{r}
data("PSID7682")

data <-
  PSID7682 %>%
  group_by(id) %>%
  mutate(period = as.numeric(year), # yearを連続変数化
         treatment.time = if_else(married == "yes",
                                  period,
                                  999),
         treatment.time = min(treatment.time)
         ) %>% # 結婚したperiodを作成(結婚しなかったサンプル = 9999)
  ungroup
```

- 記述統計

```{r}
table(data$treatment.time)
```

## Two-way fixed effect model in the two-by-two case

- 2時点・2グループデータ

```{r}
data %>%
  filter(period <= 2) %>%
  filter(treatment.time == 999 |
           treatment.time == 2) %>%
  mutate(D = if_else(period >= treatment.time,
                     1,
                     0)
         ) %>%
  lm_robust(weeks ~ 
              D +
              factor(period),
            data = .,
            clusters = id,
            fixed_effects = id)
```

### Two-way fixed effect model

- 2時点・2グループデータ

```{r}
data %>%
  filter(treatment.time != 1) %>%
  mutate(D = if_else(period >= treatment.time,
                     1,
                     0)
         ) %>%
  lm_robust(weeks ~ 
              D +
              factor(period),
            data = .,
            clusters = id,
            fixed_effects = id)
```


## Weighted two-way fixed effect model

```{r}
fit <-
  data %>%
  filter(treatment.time != 1) %>%
  mutate(id = as.numeric(id),
         treatment.time = if_else(treatment.time == 999,
                                  0,
                                  treatment.time)
         ) %>%
  att_gt(yname = "weeks",
         tname = "period",
         idname = "id",
         gname = "treatment.time",
         data = .,
         control_group = 999)

fit
```

```{r}
aggte(fit, 
      type = "simple") %>%
  summary
```

```{r}
aggte(fit, 
      type = "dynamic") %>%
  ggdid
```
