# 概念整理 {#intro}

- 本稿では条件付き母平均関数の推定とその応用に焦点を絞る

- 条件付き母平均関数は以下で定義される

$$\mu(w)=E[Y_i|W_i=w]$$

- 一般にデータから、条件付き母平均関数を”完璧”に推定することは不可能である。このため”妥協を伴う”ゴールを適切に設定する必要がある

## 推定のゴール

- 大きく二つのゴールがある

  - 条件付き母平均関数 $\mu(w)$ の近似： 平均二乗誤差 $E[(\mu(w) - f(w))^2]$ を可能な限り削減する様に $f(w)$ を推定

  - 関心のある変数 $d$ について、記述モデルを推定: $\tau(d,d',x)=\mu(d,x)-\mu(d',x)$ の重要な”特徴”を捉える単純化されたモデルを推定する

## 応用方法

- 推定結果は以下のように応用できる

- $f(w)$ の応用: 

  - $Y$ の予測：データと同じ母集団から抽出された新たにサンプリ $i$ について、 $W_i$ から $Y_i$ を予測するる。予測精度を平均二乗誤差で測定するのであれば母平均関数 $\mu(w)$ が最善の予測関数となり、その近似関数 $f(w)$ が現実的な予測値となる

- $\tau(x)$ の応用:

  - $D$ が異なるグループ間での $Y$ についての”格差"：変数$D_i$の値が異なる集団間において、結果変数$Y_i$の分布がどの程度異なっているのか、推定する。またこの際に、直接的な関心ではない変数群$X_i$を”一定”としたもとで、比較したいとする。全ての変数 $W$ を考慮する訳ではないので、 $\tau(d,d',x)$ を適切に推定する必要がある
  
  - $D$ が $Y$ に与える因果効果：ある集団の変数$D$を変化させた場合、結果変数$Y$の分布がどのように変化するのか、因果効果を推定する。
  
    - 注意:因果効果を推定する際には、識別を議論する必要がある。 $\tau(d,d',x)$ は以下の識別の仮定の下で、$X_i=x$ を満たす集団内での平均因果効果と一致する

    1. $0<\Pr[D_i=d|X_i]<1$: サブグループにおいても、原因変数の値にバリエーションが存在する。
  
    2. $X$で条件づけた場合、潜在結果関数と原因変数の実現値が独立している$Y_i(d)\perp D_i|X_i=x$
  
    - 十分条件：同じ$X$グループ内では、$D$の値がランダムに決定されている

    - 上記の仮定は、"selection-on-observable" と呼ばれ、多くの実践で用いられている。 この仮定の下では、$\tau(d,d',x)$ を適切に推定する必要がある。
E[Y_i|X_i=x]-\lim_{x\downarrow c}E[Y_i|X_i=x]$$
