# 概念整理 {#intro}

- 本稿では条件付き母平均関数の推定とその応用に焦点を絞る

- 条件付き母平均関数は以下で定義される

$$\mu(w)=E[Y_i|W_i=w]$$

- 一般にデータから、条件付き母平均関数を”完璧”に推定することは不可能である。このため”妥協を伴う”ゴールを適切に設定する必要がある

## 推定のゴール

- 大きく二つのゴールがある

  - 条件付き母平均関数 $\mu(w)$ の近似： 平均二乗誤差 $E[(\mu(w) - f(w))^2]$ を可能な限り削減する様に $f(w)$ を推定

  - 関心のある変数 $d$ についての特徴を推定: $\tau(d,d',x)=\mu(d,x)-\mu(d',x)$ の”特徴”を推定する


## 応用方法

- 大きく３つの応用がある

  - $Y$ の予測 $\rightarrow f(w)$ の推定：データと同じ母集団から抽出された新たにサンプリ $i$ について、 $W_i$ から $Y_i$ を予測するる。予測精度を平均二乗誤差で測定するのであれば母平均関数 $\mu(w)$ が最善の予測関数となり、その近似関数 $f(w)$ が現実的な予測値となる
  
  - $D$ が異なるグループ間での $Y$ についての”格差" $\rightarrow \tau(d,x)$ の推定：変数$D_i$の値が異なる集団間において、結果変数$Y_i$の分布がどの程度異なっているのか、推定する。またこの際に、直接的な関心ではない変数群$X_i$を”一定”としたもとで、比較したいとする。全ての変数 $W$ を考慮する訳ではないので、 $\tau(d,d',x)$ を適切に推定する必要がある
  
  - $D$ が $Y$ に与える因果効果 $\rightarrow \tau(d,x)$ の推定：格差推定と同様に$w$

## OLSとの対比

- 有限のサンプルを用いて、多数の$W_i,X_i,D_i$で条件づけた平均値を推定するためには、なんらかの工夫が必要

- 広く用いられてきた手法は、研究者により設定された線形モデルを重回帰で推定する方法

$$E[Y_i|D_i=d,X_i=x]=\underbrace{\beta_d\times d + \beta_0 + \beta_1\times x_1+...+\beta_L \times x_L}_{線形モデル}$$

- 設定された線形モデル重回帰の推定目標を条件付き平均値の線形近似と見做す"Agnostic view" [@angrist2002covariance;@angrist2008mostly]が、重回帰を利用する説得的な理由となりうる。

  - ”正しい”回帰モデルの定式化が難しい社会科学分野においては、条件付き平均値の”真”のモデルを設定することは事実上不可能であり、線形モデルを母集団上で定義された（真の条件付き平均値）の近似モデルとみなす方が妥当であるため

- しかしながら「異なる$D$グループ間で、$X$の分布が異なる」場合、$\beta_D$の推計値が近似モデルの定式化に深刻に依存してしまう。

  - 定式化への依存を緩和するために、推定の前処理としてマッチングを行うことが有力な方法となる。
  
  - $X$の数が多い場合、伝統的なマッチング手法の有効性は失われる。
この問題を回避するためにChapter \@ref(general) では、LASSOやRandom Forestなどの予測手法の応用を紹介する。

## 因果効果 {#causal}

### 問題設定

- ある集団の変数$D$を変化させた場合、結果変数$Y$の分布がどのように変化するのか、因果効果を推定する。

- 潜在結果モデルを用いて定義する

  - $Y_i(d)$: 回答者$i$の原因変数が$d$であったときの結果変数値
  
  - $Y_i(d)-Y_i(d')$: 原因変数が$d'$から$d$に変化することの個人因果効果

### 識別の問題

- 因果効果を推定する際には、識別を議論する必要がある。

  - 識別：「仮にサンプルサイズが無限大である」場合、どのような仮定の下で因果効果を推定できるか？

#### Selection-on-observable
  
- Chapter \@ref(unique) - \@ref(hetero)では以下の仮定に基づき議論する。

  - $0<\Pr[D_i=d|X_i]<1$: サブグループにおいても、原因変数の値にバリエーションが存在する。
  
  - $X$で条件づけた場合、潜在結果関数と原因変数の実現値が独立している$Y_i(d)\perp D_i|X_i=x$
  
    - 十分条件：同じ$X$グループ内では、$D$の値がランダムに決定されている

- 以上の仮定のもとで$D$の因果効果は、$E[Y|D=d,X]-E[Y|D=d',X]$によって識別できる。

#### Regression discontinuity

- Chapter \@ref(RD)では以下の仮定に基づく手法を紹介

  - $D=\{0,1\}$とし、ある連続変数$X$についてcutoff$c$が存在するとする
  
  - $\lim_{x\uparrow c}\Pr[D_i=1|X_i=x]=1$, $\lim_{x\downarrow c}\Pr[D_i=1|X_i=x]=0$ (Sharp discontinuity)
  
    - より一般的には、原因変数の分布がcutoffの近傍で不連続に変化していれば推定できる (Fuzzy discontinuity)
    
  - $\lim_{x\uparrow c}\Pr[Y_i(d)|X_i=x]= \lim_{x\downarrow c}\Pr[Y_i(d)|X_i=x]$
  
    - 潜在結果変数の分布はcutofffの近傍で連続的に変化している

- 以上の条件の下で、cutoff$c$上の因果効果は以下のように識別される

$$E[Y_i(1)-Y_i(0)|X_i=c]=\lim_{x\uparrow c}E[Y_i|X_i=x]-\lim_{x\downarrow c}E[Y_i|X_i=x]$$

#### Pallarel trend

- Chapter \@ref(panel)　では平行トレンドに基づく推定方法を紹介する。

- 2期間のパネルデータを想定し、Treatment/Control groupが存在するとする。

  - 原因変数の値は以下を満たす。 $D_{i\in T,0}=D_{i\in C,0}=0$、$D_{i\in T,1}=1, D_{i\in C,1}=0$、ただし$i\in T$はTreatment、$i\in C$はControl groupに所属することを示す。
  
  - $E[Y_{i\in T,1}(0)-Y_{i\in T,0}(0)]=E[Y_{i\in C,1}(0)-Y_{i\in C,0}(0)]$

### 推定の問題

- 識別できたとしても、推定が困難な場合がある。

  - Selection-on-observableに基づく推定では、しばしば大量の$X$をコントロールする必要がある。この場合、比較と同じような推定上の問題を抱え、その解決策も共有する。

- Regression discontinuityでは、$\lim_{x\uparrow c}E[Y_i|X_i=x]$、$\lim_{x\downarrow c}E[Y_i|X_i=x]$を以下に推定するかが問題となる。Chapter \@ref(panel) ではもっとも標準的な局所的外挿による推定法を紹介する
